Added quick peek
degeneratehyperbola/NEPS pull request #101
Opened 2022-01-30 14:48 UTC by SK0lll

There is still room for improvement but a basic quick peek should help with some HvH.

2022-01-30 17:55 UTC, degeneratehyperbola requested changes
Amazing, didn't try it out yet, hope to see it working 👍🏿

2022-01-30 17:55 UTC, degeneratehyperbola commented on NEPS/Config.cpp
> +	WRITE("QuickPeekKey", QuickPeekKey);
Here it is "QuickPeekKey" but when reading it is the same but with spaces "Quick Peek Key", this causes it to fail to load and reset to its default value

2022-01-30 17:55 UTC, degeneratehyperbola commented on NEPS/Hacks/Misc.cpp
> +}
Oh, I see you did the way I would, even though it's a bit more complex, you managed to do it right, my respect 👍🏿

2022-01-30 17:55 UTC, degeneratehyperbola commented on NEPS/Hacks/Misc.cpp
> +std::vector<custom_cmd>usercmds_for_quickpeek;
There is no practical reason to do so but just to keep the overall coding style, you should make these vars static

2022-02-08 04:48 UTC, wuuxiehacker303 commented
I remember the third task to be completed is“"Mode", &config->movement.quickpeek.mode, "Direct\0Backstep\0"”，Why did cancel the update；     0v0

2022-02-08 10:51 UTC, degeneratehyperbola commented
Ok I am merging it and am going to polish it up a bit afterwards. You don't seem to follow the Osiris's code style but that's just nitpicking at this point. Good work!

2022-02-08 14:23 UTC, merged